import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {filterByProfile} from '../public/js/profile-filter.js';
const products=JSON.parse(readFileSync(new URL('../public/demo-products.json',import.meta.url)));
const base={goal:'gain',frequency:'medium',protein:'yes',calories:'no',diet:'none',avoid:'none',age:'adult',health:'no',budget:'all'};
const basic=filterByProfile(products,base);
assert(basic.matches.some(p=>p.category==='Whey'));
assert(basic.matches.some(p=>p.category==='Creatina'));
assert(!basic.matches.some(p=>p.category==='Vitaminas'||p.category==='Pré-Treino'));
assert.equal(filterByProfile(products,{...base,budget:'7000'}).matches.every(p=>p.price_cents<=7000),true);
assert.deepEqual(filterByProfile(products,{...base,age:'minor'}).matches,[]);
assert.deepEqual(filterByProfile(products,{...base,health:'yes'}).matches,[]);
assert.deepEqual(filterByProfile(products,{...base,avoid:'milk'},{}).matches,[]);
const labels={whey300:{verified:true,diet:{vegetarian:true,vegan:false},free_from:{milk:false,lactose:false,gluten:true},allergens:{contains:['milk'],may_contain:[]}}};
assert.deepEqual(filterByProfile(products,{...base,avoid:'milk'},labels).matches,[]);
assert.deepEqual(filterByProfile(products,{...base,diet:'vegan'},labels).matches,[]);
assert.deepEqual(filterByProfile(products,{...base,diet:'vegetarian'},labels).matches.map(p=>p.id),['whey300']);
assert.deepEqual(filterByProfile(products,{...base,avoid:'gluten'},labels).matches.map(p=>p.id),['whey300']);
console.log('Filtros de catálogo: OK');
