import assert from 'node:assert/strict';
import fs from 'node:fs';
// Load ESM without requiring changes to the PHP project's package configuration.
const code=fs.readFileSync(new URL('../public/js/profile-filter.js',import.meta.url),'utf8');
const {filterByProfile,satisfies,questions,priceBounds}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const products=JSON.parse(fs.readFileSync(new URL('../public/demo-products.json',import.meta.url),'utf8'));
assert.equal(questions.length,8);
assert.equal(questions.filter(q=>q[3]).length,2);
assert.equal(filterByProfile(products,{}).matches.length,27);
const result=filterByProfile(products,{category:'Whey',objective:'protein',restrictions:['lactose'],budget:'all'});
assert(!result.matches.some(p=>p.category==='Whey'));
assert(result.warnings.some(s=>s.includes('categoria')));
assert.equal(filterByProfile(products,{restrictions:['vegan','gluten'],avoid:['caffeine'],budget:'5000-10000'}).matches.length,4);
assert.equal(filterByProfile(products,{avoid:['sugar']}).matches.length,4);
assert.equal(filterByProfile(products,{budget:'0-5000'}).matches.length,8);
assert(filterByProfile(products,{category:'Whey',objective:'protein',format:'powder'}).matches.slice(0,4).every(p=>p.category==='Whey'));
assert.equal(filterByProfile(products,{flavor:'strawberry'}).matches[0].id,'vitaminaMorango');
assert.equal(filterByProfile(products,{sport:'strength'}).matches[0].category,'Creatina');
assert.equal(filterByProfile(products,{}, {category:'Creatina',sort:'price-down'}).matches[0].id,'creatina2kg');
assert.equal(filterByProfile(products,{}, {q:'PRE treino'}).matches.length,3); // punctuation and accents are normalized
assert.equal(filterByProfile(products,{}, {q:'vitaminas'}).matches.length,5);
assert(questions[2][2].some(([value])=>value==='Pré-Treino'));
assert(questions[2][2].some(([value])=>value==='Hipercalórico'));
assert(!questions[2][2].some(([value])=>value==='Acessórios'));
assert.equal(filterByProfile(products,{}, {q:'barra chocolate'}).matches.length,1);
assert.equal(filterByProfile(products,{}, {q:'vegano frutas'}).matches[0].id,'barra-vegan-frutas50');
assert.equal(filterByProfile(products,{}, {format:'tablet'}).matches[0].id,'multi-comprimidos60');
assert.equal(filterByProfile(products,{}, {category:'Barras proteicas'}).matches.length,2);
assert.equal(filterByProfile(products,{}, {brand:'BROWTH',format:'powder'}).matches.length,19);
assert.equal(filterByProfile(products,{}, {rating:'4'}).matches.length,0);
assert.equal(filterByProfile(products,{}, {sort:'sales'}).warnings.length,1);
const unknown={id:'x',name:'Unknown',category:'Whey',price_cents:5000,stock:0,active:true};
assert.equal(filterByProfile([unknown],{}).matches.length,1);
assert.equal(filterByProfile([unknown],{}, {available:'yes'}).matches.length,0);
assert.equal(satisfies(unknown,['lactose']),false);
assert.equal(satisfies(unknown,[],['sugar']),false);
assert.equal(satisfies(unknown,['vegan']),false);
const conflict={...unknown,catalog_attributes:{free_from:{gluten:true},allergens:{contains:[],may_contain:['gluten']}}};
assert.equal(satisfies(conflict,['gluten']),false);
assert.equal(filterByProfile([{...unknown,active:false}],{}).matches.length,0);
assert.equal(filterByProfile(products,{budget:'invalid'}).matches.length,0);
assert.deepEqual(priceBounds('25000-plus'),[25001,Infinity]);
console.log('8 perguntas, restrições combinadas, dados ausentes, ordenação e filtros manuais: OK');
